import Head from "next/head";
import Portada from "../components/Portada";
import Nav from "../components/Nav";
import About from "../components/About";
import What from "../components/What";
import Clientes from "../components/Clientes";
import Working from "../components/Working";
import Footer from "../components/Footer";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Nav />
        <Portada />
        <div className="bg-[#101010] flex  pl-[120px] gap-5">
          <div className="bg-[#fa3636] relative w-[2px] h-[60px]"></div>
          <h2 className="text-[9px] uppercase font-bold text-[#fff]">
            Show me more
          </h2>
        </div>
        <About />
        <What />
        <Clientes />
        <Working />
      </body>
      <footer>
        <Footer />
      </footer>
    </>
  );
}
